sonarqube:
  community:
    enabled: true
  ingress:
    enabled: true
    hosts:
    - name: sonar.devops.cl
      path: "/"
    tls: []
    ingressClassName: nginx
  monitoringPasscodeSecretName: sonarqube-monitoring
  monitoringPasscodeSecretKey: passcode
  jdbcOverwrite:
    enabled: true
    jdbcUrl: "jdbc:postgresql://main-postgres-rw.databases.svc.cluster.local:5432/db-sonar?sslmode=require"
    jdbcUsername: sonar-user
    jdbcSecretName: sonarqube-jdbc
    jdbcSecretPasswordKey: password
